import "@babylonjs/core/Physics/v2/physicsEngineComponent";
import { Engine, FreeCamera, HavokPlugin, HemisphericLight, Scene, Vector3 } from "@babylonjs/core";
import HavokPhysics from "@babylonjs/havok";
import havokWasmUrl from "@babylonjs/havok/lib/esm/HavokPhysics.wasm?url";
import { CameraEffects } from "./effects";
import { PlayerInput } from "./input";
import { applyMouseLook, smoothLook } from "./look";
import { CAPSULE_CENTER_HEIGHT, PhysicalPlayer } from "./player";
import { selectedProfile } from "./profile";
import { buildCaveEntrance, type WorldInfo } from "./caveEntrance";
import { buildChamber } from "./world";

type Snapshot = { world:string; spawnPosition:{x:number;y:number;z:number}; playerPosition:{x:number;y:number;z:number}; cameraPosition:{x:number;y:number;z:number}; velocity:{x:number;y:number;z:number}; planarSpeed:number; grounded:boolean; activeInputs:Record<string,boolean>; cameraYaw:number; cameraPitch:number; targetYaw:number; targetPitch:number; fov:number; headBobOffset:number; breathingOffset:number; pointerLock:boolean; selectedProfile:string; doorState:string; doorAngle:number; interactionAvailable:boolean; doorCollisionEnabled:boolean; doorwayTraversable:boolean; distanceToDoor:number; activeDoorAnimationCount:number; activeGameLoopCount:number; inputListenerCount:number; frameTimeSummary:{average:number;max:number}; drawCalls:number; activeMeshes:number; physicsBodyCount:number };
declare global { interface Window { __CAVE_GAME_TEST__?: { getSnapshot: () => Readonly<Snapshot> } } }
export class CaveGame {
  private engine: Engine; private scene: Scene; private player!: PhysicalPlayer; private input!: PlayerInput; private camera!: FreeCamera; private effects = new CameraEffects(); private profile; private world!: WorldInfo; private prompt!:HTMLDivElement; private interaction=false; private yaw = 0; private pitch = 0; private targetYaw = 0; private targetPitch = 0; private times:number[]=[]; private started = false;
  constructor(private readonly canvas: HTMLCanvasElement, private readonly overlay: HTMLButtonElement) { const params=new URLSearchParams(location.search); this.profile=selectedProfile(params.get("profile")); const review=params.get("review"); this.review=review!==null; this.chamber=review==="movement"||review==="chamber"; this.engine=new Engine(canvas, true); this.scene=new Scene(this.engine); }
  private readonly review: boolean;
  private readonly chamber: boolean;
  async start() { const havok = await HavokPhysics({ locateFile: () => havokWasmUrl }); this.scene.enablePhysics(new Vector3(0,-9.81,0), new HavokPlugin(true, havok)); if(this.chamber){ buildChamber(this.scene); new HemisphericLight("chamber-light", new Vector3(0,1,0), this.scene).intensity=.65; this.world={name:"chamber",spawn:new Vector3(0,.9,7),yaw:0}; } else this.world=buildCaveEntrance(this.scene); this.player=new PhysicalPlayer(this.scene,this.world.spawn); this.yaw=this.targetYaw=this.world.yaw; this.camera=new FreeCamera("eyes", this.player.position.add(new Vector3(0,this.profile.eyeHeight-CAPSULE_CENTER_HEIGHT,0)),this.scene); this.camera.fov=this.profile.fov; this.camera.minZ=.05; this.prompt=document.createElement("div");this.prompt.id="interaction-prompt";this.prompt.textContent="PRESS ENTER TO OPEN";document.body.append(this.prompt); this.input=new PlayerInput(()=>this.reset(),this.review,()=>{if(this.interaction)this.world.door?.interact();}); this.canvas.addEventListener("mousemove", this.onMouse); this.overlay.addEventListener("click",this.enter); this.engine.runRenderLoop(this.frame); this.started=true; if(this.review) window.__CAVE_GAME_TEST__={getSnapshot:()=>Object.freeze({...this.snapshot()})}; }
  private enter = () => { this.canvas.requestPointerLock(); this.overlay.classList.add("hidden"); };
  private onMouse = (event: MouseEvent) => { if(document.pointerLockElement!==this.canvas)return; const look=applyMouseLook({yaw:this.targetYaw,pitch:this.targetPitch},event.movementX,event.movementY,this.profile); this.targetYaw=look.yaw; this.targetPitch=look.pitch; };
  private frame=()=>{ const dt=Math.min(.05,this.engine.getDeltaTime()/1000 || 1/60); this.yaw=smoothLook(this.yaw,this.targetYaw,dt,this.profile.lookResponse); this.pitch=smoothLook(this.pitch,this.targetPitch,dt,this.profile.lookResponse); const {speed,actualMovement}=this.player.update(dt,this.input.state,this.yaw,this.profile); this.world.door?.update(dt); const door=this.world.door; const to=door?door.position.subtract(this.player.position):Vector3.Zero(); to.y=0; const facing=door?Vector3.Dot(new Vector3(Math.sin(this.yaw),0,Math.cos(this.yaw)),to.normalize())>.45:false; this.interaction=!!door&&door.state==="CLOSED"&&to.length()<3.1&&facing&&document.pointerLockElement===this.canvas; this.prompt.classList.toggle("visible",this.interaction); const offsets=this.effects.update(dt,speed,actualMovement,this.input.state.backward,this.profile); this.camera.position.copyFrom(this.player.position); this.camera.position.y+=this.profile.eyeHeight-CAPSULE_CENTER_HEIGHT+offsets.bob+offsets.breathing; this.camera.rotation.set(this.pitch,this.yaw,0); this.times.push(dt*1000); if(this.times.length>120)this.times.shift(); if(document.pointerLockElement!==this.canvas)this.overlay.classList.remove("hidden"); this.scene.render(); };
  reset(){ this.player.reset(this.world.spawn); this.world.door?.reset(); this.input.clear(); this.effects.reset(); this.interaction=false;this.prompt.classList.remove("visible"); this.yaw=this.world.yaw; this.pitch=0; this.targetYaw=this.world.yaw; this.targetPitch=0; }
  private snapshot():Snapshot { const e=this.effects.offsets; const counter=(this.engine as unknown as {_drawCalls?:{current?:number}})._drawCalls; const door=this.world.door; return {world:this.world.name,spawnPosition:{x:this.world.spawn.x,y:this.world.spawn.y,z:this.world.spawn.z},playerPosition:{x:this.player.position.x,y:this.player.position.y,z:this.player.position.z},cameraPosition:{x:this.camera.position.x,y:this.camera.position.y,z:this.camera.position.z},velocity:{x:this.player.velocity.x,y:this.player.velocity.y,z:this.player.velocity.z},planarSpeed:Math.hypot(this.player.velocity.x,this.player.velocity.z),grounded:this.player.grounded,activeInputs:{...this.input.state},cameraYaw:this.yaw,cameraPitch:this.pitch,targetYaw:this.targetYaw,targetPitch:this.targetPitch,fov:this.camera.fov,headBobOffset:e.bob,breathingOffset:e.breathing,pointerLock:document.pointerLockElement===this.canvas,selectedProfile:this.profile.name,doorState:door?.state??"NONE",doorAngle:door?.angle??0,interactionAvailable:this.interaction,doorCollisionEnabled:door?.sealEnabled??false,doorwayTraversable:door?.traversable??false,distanceToDoor:door?Vector3.Distance(this.player.position,door.position):Infinity,activeDoorAnimationCount:door?.state==="OPENING"?1:0,activeGameLoopCount:this.started?1:0,inputListenerCount:this.input.listenerCount+2,frameTimeSummary:{average:this.times.reduce((a,b)=>a+b,0)/(this.times.length||1),max:Math.max(0,...this.times)},drawCalls:counter?.current ?? 0,activeMeshes:this.scene.meshes.length,physicsBodyCount:this.chamber?9:15}; }
}
